assigness: []
harvest_options:
  goldcopy: false
  path: s3://ooi-data
  refresh: true
  test: false
instrument: RS01SUM2-MJ01B-12-ADCPSK101
stream:
  method: streamed
  name: adcp_engineering
workflow_config:
  schedule: 0 0 * * *
